### ISSUE TITLE
Access Search Console Data?

### ISSUE THREAD

**Issue by shorepound** [tpitale/legato#138]
https://support.google.com/analytics/answer/1308626?hl=en&ref_topic=1308589

**Comment by tpitale** [comment]
It appears that this is a distinct API https://developers.google.com/webmaster-tools/search-console-api-original/v3/

But, if you queried that API, you could possibly join the data together with the `landing_page` dimension from analytics you get from Legato. The details of that join appear to be described in the document you link to.

**Comment by tpitale** [comment]
This appears to be the same answer from 3 years ago https://stackoverflow.com/questions/38997326/google-analytics-reporting-api-search-console-dimensions-metrics

I can't find anywhere in the docs that might indicate otherwise. If you find something in the core reporting API, let me know and I can take a look.
